[project]
name = "onehealth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.0",
    "langgraph>=1.2.0",
    "langgraph-cli[inmem]>=0.4.26",
    "python-dotenv>=1.0.0",
    "httpx>=0.27.0",
    "langchain-openrouter>=0.2.3",
    "firecrawl>=4.26.0",
    "supabase>=2.30.0",
    "stagehand>=3.20.0",
    "langchain-openai>=1.2.1",
]
