"""Postgres schema helpers for webhook and booking persistence."""

from __future__ import annotations

import os
from functools import lru_cache

import psycopg


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS telegram_updates (
    update_id BIGINT PRIMARY KEY,
    chat_id TEXT,
    thread_id TEXT,
    raw_update JSONB NOT NULL,
    message JSONB,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'processing', 'done', 'failed', 'ignored')),
    attempts INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    ignored_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS telegram_updates_status_idx
    ON telegram_updates (status, updated_at);

CREATE INDEX IF NOT EXISTS telegram_updates_thread_idx
    ON telegram_updates (thread_id, update_id);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_key TEXT NOT NULL UNIQUE,
    chat_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'booked', 'failed')),
    details JSONB NOT NULL,
    nexhealth_appointment_id TEXT,
    nexhealth_payload JSONB,
    nexhealth_response JSONB,
    error TEXT,
    attempts INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS appointments_chat_id_idx
    ON appointments (chat_id, created_at DESC);
"""


def database_url() -> str:
    url = os.getenv("DATABASE_URL")
    if not url:
        raise RuntimeError("Missing DATABASE_URL")
    return url


@lru_cache(maxsize=8)
def ensure_database_schema(url: str | None = None) -> None:
    with psycopg.connect(url or database_url()) as conn:
        conn.execute(SCHEMA_SQL)
        conn.commit()
